# language: python
# python:
#   - "2.7"
# install:
#   - "pip install -r requirements.txt"
#   - "mkdir -p ~/.kube"
#   - "ln -s $PWD/test/data/kube_config.yaml ~/.kube/config"
# script: "nosetests test/"
# cache: pip
