apiVersion: v1
kind: ReplicationController
metadata:
  name: autoscaler
spec:
  replicas: 1
  selector:
    app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
        openai/do-not-drain: "true"
    spec:
      containers:
      - name: autoscaler
        image: wbuchwalter/kubernetes-acs-engine-autoscaler
        env:
        - name: AZURE_SP_APP_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-app-id
        - name: AZURE_SP_SECRET
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-secret
        - name: AZURE_SP_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-tenant-id       
        - name: PYKUBE_KUBERNETES_SERVICE_HOST
          value: 10.240.255.15
        command:
            - python
            - main.py
            - --resource-group 
            - <your-group-name>
            - --template-file-url
            - <your-template-file-url>
            - --parameters-file-url
            - <your-parametes-file-url>
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: Default  # Don't use cluster DNS.