apiVersion: v1
kind: ReplicationController
metadata:
  name: autoscaler
spec:
  replicas: 1
  selector:
    app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
        openai/do-not-drain: "true"
    spec:
      containers:
      - name: autoscaler
        image: wbuchwalter/autoscaler
        env:
        - name: AZURE_SP_APP_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-app-id
        - name: AZURE_SP_SECRET
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-secret
        - name: AZURE_SP_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-tenant-id       
        - name: PYKUBE_KUBERNETES_SERVICE_HOST
          value: 10.240.255.15
          # value: kubernetes.default
        - name: DATADOG_TAGS
          value: env:sci
        command:
            - python
            - main.py
            - --resource-group 
            - gpucluster
            - --template-file-url
            - https://gist.githubusercontent.com/wbuchwalter/4b3f2a2a9e422343b7ece82b143dd70e/raw/6d169452becb3e6990c017620f34cde3ab12d467/template.json
            - --parameters-file-url
            - https://gist.githubusercontent.com/wbuchwalter/6f96d10ab062b741a7e72f4b566e8a3d/raw/ca219463073dbe535b129ac2272044ff22c10034/params.json
            - --over-provision
            - "0"
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: Default  # Don't use cluster DNS.
