apiVersion: v1
kind: ReplicationController
metadata:
  name: autoscaler
spec:
  replicas: 1
  selector:
    app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
        openai/do-not-drain: "true"
    spec:
      containers:
      - name: autoscaler
        image: wbuchwalter/kubernetes-acs-engine-autoscaler:dev
        env:
        - name: AZURE_SP_APP_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-app-id
        - name: AZURE_SP_SECRET
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-secret
        - name: AZURE_SP_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: azure-sp-tenant-id       
        - name: PYKUBE_KUBERNETES_SERVICE_HOST
          value: 10.240.255.5
        command:
            - python
            - main.py
            - --resource-group 
            - wibuchk8s2
            - --template-file-url
            - https://gist.githubusercontent.com/wbuchwalter/4b3f2a2a9e422343b7ece82b143dd70e/raw/1a98ac637be0404aad0b95a4407a346ab7462c01/template.json
            - --parameters-file-url
            - https://gist.githubusercontent.com/wbuchwalter/6f96d10ab062b741a7e72f4b566e8a3d/raw/c6a3e6c8b23be9d07d6f7c0a7a7e689a8fddf6f7/params.json
            - --debug
            - -vvv
            - --sleep
            - '20'
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: Default  # Don't use cluster DNS.
